// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export * from '/Users/liaoxiaojuan/work/G2Plot/site/node_modules/_@antv_dumi-theme-antv@0.3.4@@antv/dumi-theme-antv/dist/slots/CodePreview/index.js';
