// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/liaoxiaojuan/work/G2Plot/site/node_modules/_dumi@2.0.10@dumi/theme-default/slots/PreviewerActionsExtra/index.js';
