// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { demos as dm0, frontmatter as fm0, toc as toc0, texts as txt0 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/annotations/base-annotation.en.md?type=meta';
import { demos as dm1, frontmatter as fm1, toc as toc1, texts as txt1 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/annotations/base-annotation.zh.md?type=meta';
import { demos as dm2, frontmatter as fm2, toc as toc2, texts as txt2 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/annotations/region-filter.en.md?type=meta';
import { demos as dm3, frontmatter as fm3, toc as toc3, texts as txt3 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/annotations/region-filter.zh.md?type=meta';
import { demos as dm4, frontmatter as fm4, toc as toc4, texts as txt4 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/annotations/data-marker.en.md?type=meta';
import { demos as dm5, frontmatter as fm5, toc as toc5, texts as txt5 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/annotations/data-marker.zh.md?type=meta';
import { demos as dm6, frontmatter as fm6, toc as toc6, texts as txt6 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/annotations/data-region.en.md?type=meta';
import { demos as dm7, frontmatter as fm7, toc as toc7, texts as txt7 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/annotations/data-region.zh.md?type=meta';
import { demos as dm8, frontmatter as fm8, toc as toc8, texts as txt8 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/components/conversion-tag.en.md?type=meta';
import { demos as dm9, frontmatter as fm9, toc as toc9, texts as txt9 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/components/conversion-tag.zh.md?type=meta';
import { demos as dm10, frontmatter as fm10, toc as toc10, texts as txt10 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/bidirectional-bar.en.md?type=meta';
import { demos as dm11, frontmatter as fm11, toc as toc11, texts as txt11 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/bidirectional-bar.zh.md?type=meta';
import { demos as dm12, frontmatter as fm12, toc as toc12, texts as txt12 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/components/annotations.en.md?type=meta';
import { demos as dm13, frontmatter as fm13, toc as toc13, texts as txt13 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/components/annotations.zh.md?type=meta';
import { demos as dm14, frontmatter as fm14, toc as toc14, texts as txt14 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/annotations/region.en.md?type=meta';
import { demos as dm15, frontmatter as fm15, toc as toc15, texts as txt15 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/annotations/region.zh.md?type=meta';
import { demos as dm16, frontmatter as fm16, toc as toc16, texts as txt16 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/component-progress.en.md?type=meta';
import { demos as dm17, frontmatter as fm17, toc as toc17, texts as txt17 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/component-progress.zh.md?type=meta';
import { demos as dm18, frontmatter as fm18, toc as toc18, texts as txt18 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/advanced-plots/facet.en.md?type=meta';
import { demos as dm19, frontmatter as fm19, toc as toc19, texts as txt19 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/advanced-plots/facet.zh.md?type=meta';
import { demos as dm20, frontmatter as fm20, toc as toc20, texts as txt20 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/components/scrollbar.en.md?type=meta';
import { demos as dm21, frontmatter as fm21, toc as toc21, texts as txt21 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/components/scrollbar.zh.md?type=meta';
import { demos as dm22, frontmatter as fm22, toc as toc22, texts as txt22 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/components/statistic.en.md?type=meta';
import { demos as dm23, frontmatter as fm23, toc as toc23, texts as txt23 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/components/statistic.zh.md?type=meta';
import { demos as dm24, frontmatter as fm24, toc as toc24, texts as txt24 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/options/interactions.en.md?type=meta';
import { demos as dm25, frontmatter as fm25, toc as toc25, texts as txt25 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/options/interactions.zh.md?type=meta';
import { demos as dm26, frontmatter as fm26, toc as toc26, texts as txt26 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/circle-packing.en.md?type=meta';
import { demos as dm27, frontmatter as fm27, toc as toc27, texts as txt27 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/circle-packing.zh.md?type=meta';
import { demos as dm28, frontmatter as fm28, toc as toc28, texts as txt28 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/annotations/image.en.md?type=meta';
import { demos as dm29, frontmatter as fm29, toc as toc29, texts as txt29 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/annotations/image.zh.md?type=meta';
import { demos as dm30, frontmatter as fm30, toc as toc30, texts as txt30 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/annotations/shape.en.md?type=meta';
import { demos as dm31, frontmatter as fm31, toc as toc31, texts as txt31 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/annotations/shape.zh.md?type=meta';
import { demos as dm32, frontmatter as fm32, toc as toc32, texts as txt32 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/component-no-axis.en.md?type=meta';
import { demos as dm33, frontmatter as fm33, toc as toc33, texts as txt33 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/component-no-axis.zh.md?type=meta';
import { demos as dm34, frontmatter as fm34, toc as toc34, texts as txt34 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/component-polygon.en.md?type=meta';
import { demos as dm35, frontmatter as fm35, toc as toc35, texts as txt35 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/component-polygon.zh.md?type=meta';
import { demos as dm36, frontmatter as fm36, toc as toc36, texts as txt36 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/ring-progress.en.md?type=meta';
import { demos as dm37, frontmatter as fm37, toc as toc37, texts as txt37 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/ring-progress.zh.md?type=meta';
import { demos as dm38, frontmatter as fm38, toc as toc38, texts as txt38 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/annotations/html.en.md?type=meta';
import { demos as dm39, frontmatter as fm39, toc as toc39, texts as txt39 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/annotations/html.zh.md?type=meta';
import { demos as dm40, frontmatter as fm40, toc as toc40, texts as txt40 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/annotations/line.en.md?type=meta';
import { demos as dm41, frontmatter as fm41, toc as toc41, texts as txt41 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/annotations/line.zh.md?type=meta';
import { demos as dm42, frontmatter as fm42, toc as toc42, texts as txt42 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/annotations/text.en.md?type=meta';
import { demos as dm43, frontmatter as fm43, toc as toc43, texts as txt43 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/annotations/text.zh.md?type=meta';
import { demos as dm44, frontmatter as fm44, toc as toc44, texts as txt44 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/common-component.en.md?type=meta';
import { demos as dm45, frontmatter as fm45, toc as toc45, texts as txt45 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/common-component.zh.md?type=meta';
import { demos as dm46, frontmatter as fm46, toc as toc46, texts as txt46 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/advanced-plots/mix.en.md?type=meta';
import { demos as dm47, frontmatter as fm47, toc as toc47, texts as txt47 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/advanced-plots/mix.zh.md?type=meta';
import { demos as dm48, frontmatter as fm48, toc as toc48, texts as txt48 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/components/tooltip.en.md?type=meta';
import { demos as dm49, frontmatter as fm49, toc as toc49, texts as txt49 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/components/tooltip.zh.md?type=meta';
import { demos as dm50, frontmatter as fm50, toc as toc50, texts as txt50 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/annotations/arc.en.md?type=meta';
import { demos as dm51, frontmatter as fm51, toc as toc51, texts as txt51 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/annotations/arc.zh.md?type=meta';
import { demos as dm52, frontmatter as fm52, toc as toc52, texts as txt52 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/crosshairs-text.en.md?type=meta';
import { demos as dm53, frontmatter as fm53, toc as toc53, texts as txt53 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/crosshairs-text.zh.md?type=meta';
import { demos as dm54, frontmatter as fm54, toc as toc54, texts as txt54 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/getting-started.en.md?type=meta';
import { demos as dm55, frontmatter as fm55, toc as toc55, texts as txt55 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/getting-started.zh.md?type=meta';
import { demos as dm56, frontmatter as fm56, toc as toc56, texts as txt56 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/plots/histogram.en.md?type=meta';
import { demos as dm57, frontmatter as fm57, toc as toc57, texts as txt57 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/plots/histogram.zh.md?type=meta';
import { demos as dm58, frontmatter as fm58, toc as toc58, texts as txt58 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/plots/waterfall.en.md?type=meta';
import { demos as dm59, frontmatter as fm59, toc as toc59, texts as txt59 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/plots/waterfall.zh.md?type=meta';
import { demos as dm60, frontmatter as fm60, toc as toc60, texts as txt60 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/components/legend.en.md?type=meta';
import { demos as dm61, frontmatter as fm61, toc as toc61, texts as txt61 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/components/legend.zh.md?type=meta';
import { demos as dm62, frontmatter as fm62, toc as toc62, texts as txt62 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/components/slider.en.md?type=meta';
import { demos as dm63, frontmatter as fm63, toc as toc63, texts as txt63 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/components/slider.zh.md?type=meta';
import { demos as dm64, frontmatter as fm64, toc as toc64, texts as txt64 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/options/animation.en.md?type=meta';
import { demos as dm65, frontmatter as fm65, toc as toc65, texts as txt65 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/options/animation.zh.md?type=meta';
import { demos as dm66, frontmatter as fm66, toc as toc66, texts as txt66 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/tiny-column.en.md?type=meta';
import { demos as dm67, frontmatter as fm67, toc as toc67, texts as txt67 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/tiny-column.zh.md?type=meta';
import { demos as dm68, frontmatter as fm68, toc as toc68, texts as txt68 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/animate-option.en.md?type=meta';
import { demos as dm69, frontmatter as fm69, toc as toc69, texts as txt69 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/animate-option.zh.md?type=meta';
import { demos as dm70, frontmatter as fm70, toc as toc70, texts as txt70 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/component-tiny.en.md?type=meta';
import { demos as dm71, frontmatter as fm71, toc as toc71, texts as txt71 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/component-tiny.zh.md?type=meta';
import { demos as dm72, frontmatter as fm72, toc as toc72, texts as txt72 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/connected-area.en.md?type=meta';
import { demos as dm73, frontmatter as fm73, toc as toc73, texts as txt73 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/connected-area.zh.md?type=meta';
import { demos as dm74, frontmatter as fm74, toc as toc74, texts as txt74 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/conversion-tag.en.md?type=meta';
import { demos as dm75, frontmatter as fm75, toc as toc75, texts as txt75 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/conversion-tag.zh.md?type=meta';
import { demos as dm76, frontmatter as fm76, toc as toc76, texts as txt76 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/components/label.en.md?type=meta';
import { demos as dm77, frontmatter as fm77, toc as toc77, texts as txt77 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/components/label.zh.md?type=meta';
import { demos as dm78, frontmatter as fm78, toc as toc78, texts as txt78 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/radial-bar.en.md?type=meta';
import { demos as dm79, frontmatter as fm79, toc as toc79, texts as txt79 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/radial-bar.zh.md?type=meta';
import { demos as dm80, frontmatter as fm80, toc as toc80, texts as txt80 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/word-cloud.en.md?type=meta';
import { demos as dm81, frontmatter as fm81, toc as toc81, texts as txt81 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/word-cloud.zh.md?type=meta';
import { demos as dm82, frontmatter as fm82, toc as toc82, texts as txt82 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/chart-methods.en.md?type=meta';
import { demos as dm83, frontmatter as fm83, toc as toc83, texts as txt83 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/chart-methods.zh.md?type=meta';
import { demos as dm84, frontmatter as fm84, toc as toc84, texts as txt84 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/chart-options.en.md?type=meta';
import { demos as dm85, frontmatter as fm85, toc as toc85, texts as txt85 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/chart-options.zh.md?type=meta';
import { demos as dm86, frontmatter as fm86, toc as toc86, texts as txt86 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/plots/heatmap.en.md?type=meta';
import { demos as dm87, frontmatter as fm87, toc as toc87, texts as txt87 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/plots/heatmap.zh.md?type=meta';
import { demos as dm88, frontmatter as fm88, toc as toc88, texts as txt88 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/plots/scatter.en.md?type=meta';
import { demos as dm89, frontmatter as fm89, toc as toc89, texts as txt89 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/plots/scatter.zh.md?type=meta';
import { demos as dm90, frontmatter as fm90, toc as toc90, texts as txt90 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/components/axis.en.md?type=meta';
import { demos as dm91, frontmatter as fm91, toc as toc91, texts as txt91 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/components/axis.zh.md?type=meta';
import { demos as dm92, frontmatter as fm92, toc as toc92, texts as txt92 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/options/pattern.en.md?type=meta';
import { demos as dm93, frontmatter as fm93, toc as toc93, texts as txt93 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/options/pattern.zh.md?type=meta';
import { demos as dm94, frontmatter as fm94, toc as toc94, texts as txt94 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/dual-axes.en.md?type=meta';
import { demos as dm95, frontmatter as fm95, toc as toc95, texts as txt95 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/dual-axes.zh.md?type=meta';
import { demos as dm96, frontmatter as fm96, toc as toc96, texts as txt96 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/histogram.en.md?type=meta';
import { demos as dm97, frontmatter as fm97, toc as toc97, texts as txt97 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/histogram.zh.md?type=meta';
import { demos as dm98, frontmatter as fm98, toc as toc98, texts as txt98 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/tiny-area.en.md?type=meta';
import { demos as dm99, frontmatter as fm99, toc as toc99, texts as txt99 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/tiny-area.zh.md?type=meta';
import { demos as dm100, frontmatter as fm100, toc as toc100, texts as txt100 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/tiny-line.en.md?type=meta';
import { demos as dm101, frontmatter as fm101, toc as toc101, texts as txt101 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/tiny-line.zh.md?type=meta';
import { demos as dm102, frontmatter as fm102, toc as toc102, texts as txt102 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/waterfall.en.md?type=meta';
import { demos as dm103, frontmatter as fm103, toc as toc103, texts as txt103 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/waterfall.zh.md?type=meta';
import { demos as dm104, frontmatter as fm104, toc as toc104, texts as txt104 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/column-style.en.md?type=meta';
import { demos as dm105, frontmatter as fm105, toc as toc105, texts as txt105 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/column-style.zh.md?type=meta';
import { demos as dm106, frontmatter as fm106, toc as toc106, texts as txt106 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/common-iview.en.md?type=meta';
import { demos as dm107, frontmatter as fm107, toc as toc107, texts as txt107 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/common-iview.zh.md?type=meta';
import { demos as dm108, frontmatter as fm108, toc as toc108, texts as txt108 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/geometry-cfg.en.md?type=meta';
import { demos as dm109, frontmatter as fm109, toc as toc109, texts as txt109 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/geometry-cfg.zh.md?type=meta';
import { demos as dm110, frontmatter as fm110, toc as toc110, texts as txt110 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/interactions.en.md?type=meta';
import { demos as dm111, frontmatter as fm111, toc as toc111, texts as txt111 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/interactions.zh.md?type=meta';
import { demos as dm112, frontmatter as fm112, toc as toc112, texts as txt112 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/introduction.en.md?type=meta';
import { demos as dm113, frontmatter as fm113, toc as toc113, texts as txt113 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/introduction.zh.md?type=meta';
import { demos as dm114, frontmatter as fm114, toc as toc114, texts as txt114 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/plots/bullet.en.md?type=meta';
import { demos as dm115, frontmatter as fm115, toc as toc115, texts as txt115 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/plots/bullet.zh.md?type=meta';
import { demos as dm116, frontmatter as fm116, toc as toc116, texts as txt116 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/plots/column.en.md?type=meta';
import { demos as dm117, frontmatter as fm117, toc as toc117, texts as txt117 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/plots/column.zh.md?type=meta';
import { demos as dm118, frontmatter as fm118, toc as toc118, texts as txt118 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/plots/funnel.en.md?type=meta';
import { demos as dm119, frontmatter as fm119, toc as toc119, texts as txt119 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/plots/funnel.zh.md?type=meta';
import { demos as dm120, frontmatter as fm120, toc as toc120, texts as txt120 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/plots/liquid.en.md?type=meta';
import { demos as dm121, frontmatter as fm121, toc as toc121, texts as txt121 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/plots/liquid.zh.md?type=meta';
import { demos as dm122, frontmatter as fm122, toc as toc122, texts as txt122 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/plots/violin.en.md?type=meta';
import { demos as dm123, frontmatter as fm123, toc as toc123, texts as txt123 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/plots/violin.zh.md?type=meta';
import { demos as dm124, frontmatter as fm124, toc as toc124, texts as txt124 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/options/events.en.md?type=meta';
import { demos as dm125, frontmatter as fm125, toc as toc125, texts as txt125 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/options/events.zh.md?type=meta';
import { demos as dm126, frontmatter as fm126, toc as toc126, texts as txt126 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/options/g2plot.en.md?type=meta';
import { demos as dm127, frontmatter as fm127, toc as toc127, texts as txt127 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/options/g2plot.zh.md?type=meta';
import { demos as dm128, frontmatter as fm128, toc as toc128, texts as txt128 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/progress.en.md?type=meta';
import { demos as dm129, frontmatter as fm129, toc as toc129, texts as txt129 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/progress.zh.md?type=meta';
import { demos as dm130, frontmatter as fm130, toc as toc130, texts as txt130 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/sunburst.en.md?type=meta';
import { demos as dm131, frontmatter as fm131, toc as toc131, texts as txt131 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/sunburst.zh.md?type=meta';
import { demos as dm132, frontmatter as fm132, toc as toc132, texts as txt132 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/annotations.en.md?type=meta';
import { demos as dm133, frontmatter as fm133, toc as toc133, texts as txt133 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/annotations.zh.md?type=meta';
import { demos as dm134, frontmatter as fm134, toc as toc134, texts as txt134 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/facet-title.en.md?type=meta';
import { demos as dm135, frontmatter as fm135, toc as toc135, texts as txt135 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/facet-title.zh.md?type=meta';
import { demos as dm136, frontmatter as fm136, toc as toc136, texts as txt136 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/point-style.en.md?type=meta';
import { demos as dm137, frontmatter as fm137, toc as toc137, texts as txt137 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/point-style.zh.md?type=meta';
import { demos as dm138, frontmatter as fm138, toc as toc138, texts as txt138 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/shape-style.en.md?type=meta';
import { demos as dm139, frontmatter as fm139, toc as toc139, texts as txt139 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/shape-style.zh.md?type=meta';
import { demos as dm140, frontmatter as fm140, toc as toc140, texts as txt140 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/state-style.en.md?type=meta';
import { demos as dm141, frontmatter as fm141, toc as toc141, texts as txt141 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/state-style.zh.md?type=meta';
import { demos as dm142, frontmatter as fm142, toc as toc142, texts as txt142 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/plots/facet.en.md?type=meta';
import { demos as dm143, frontmatter as fm143, toc as toc143, texts as txt143 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/plots/facet.zh.md?type=meta';
import { demos as dm144, frontmatter as fm144, toc as toc144, texts as txt144 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/plots/gauge.en.md?type=meta';
import { demos as dm145, frontmatter as fm145, toc as toc145, texts as txt145 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/plots/gauge.zh.md?type=meta';
import { demos as dm146, frontmatter as fm146, toc as toc146, texts as txt146 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/plots/radar.en.md?type=meta';
import { demos as dm147, frontmatter as fm147, toc as toc147, texts as txt147 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/plots/radar.zh.md?type=meta';
import { demos as dm148, frontmatter as fm148, toc as toc148, texts as txt148 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/graphic-style.en.md?type=meta';
import { demos as dm149, frontmatter as fm149, toc as toc149, texts as txt149 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/graphic-style.zh.md?type=meta';
import { demos as dm150, frontmatter as fm150, toc as toc150, texts as txt150 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/options/shape.en.md?type=meta';
import { demos as dm151, frontmatter as fm151, toc as toc151, texts as txt151 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/options/shape.zh.md?type=meta';
import { demos as dm152, frontmatter as fm152, toc as toc152, texts as txt152 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/options/theme.en.md?type=meta';
import { demos as dm153, frontmatter as fm153, toc as toc153, texts as txt153 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/options/theme.zh.md?type=meta';
import { demos as dm154, frontmatter as fm154, toc as toc154, texts as txt154 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/heatmap.en.md?type=meta';
import { demos as dm155, frontmatter as fm155, toc as toc155, texts as txt155 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/heatmap.zh.md?type=meta';
import { demos as dm156, frontmatter as fm156, toc as toc156, texts as txt156 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/scatter.en.md?type=meta';
import { demos as dm157, frontmatter as fm157, toc as toc157, texts as txt157 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/scatter.zh.md?type=meta';
import { demos as dm158, frontmatter as fm158, toc as toc158, texts as txt158 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/treemap.en.md?type=meta';
import { demos as dm159, frontmatter as fm159, toc as toc159, texts as txt159 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/treemap.zh.md?type=meta';
import { demos as dm160, frontmatter as fm160, toc as toc160, texts as txt160 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/coordinate.en.md?type=meta';
import { demos as dm161, frontmatter as fm161, toc as toc161, texts as txt161 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/coordinate.zh.md?type=meta';
import { demos as dm162, frontmatter as fm162, toc as toc162, texts as txt162 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/drill-down.en.md?type=meta';
import { demos as dm163, frontmatter as fm163, toc as toc163, texts as txt163 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/drill-down.zh.md?type=meta';
import { demos as dm164, frontmatter as fm164, toc as toc164, texts as txt164 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/legend-cfg.en.md?type=meta';
import { demos as dm165, frontmatter as fm165, toc as toc165, texts as txt165 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/legend-cfg.zh.md?type=meta';
import { demos as dm166, frontmatter as fm166, toc as toc166, texts as txt166 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/line-style.en.md?type=meta';
import { demos as dm167, frontmatter as fm167, toc as toc167, texts as txt167 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/line-style.zh.md?type=meta';
import { demos as dm168, frontmatter as fm168, toc as toc168, texts as txt168 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/text-style.en.md?type=meta';
import { demos as dm169, frontmatter as fm169, toc as toc169, texts as txt169 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/text-style.zh.md?type=meta';
import { demos as dm170, frontmatter as fm170, toc as toc170, texts as txt170 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/plots/area.en.md?type=meta';
import { demos as dm171, frontmatter as fm171, toc as toc171, texts as txt171 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/plots/area.zh.md?type=meta';
import { demos as dm172, frontmatter as fm172, toc as toc172, texts as txt172 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/plots/line.en.md?type=meta';
import { demos as dm173, frontmatter as fm173, toc as toc173, texts as txt173 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/plots/line.zh.md?type=meta';
import { demos as dm174, frontmatter as fm174, toc as toc174, texts as txt174 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/plots/venn.en.md?type=meta';
import { demos as dm175, frontmatter as fm175, toc as toc175, texts as txt175 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/plots/venn.zh.md?type=meta';
import { demos as dm176, frontmatter as fm176, toc as toc176, texts as txt176 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/options/meta.en.md?type=meta';
import { demos as dm177, frontmatter as fm177, toc as toc177, texts as txt177 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/options/meta.zh.md?type=meta';
import { demos as dm178, frontmatter as fm178, toc as toc178, texts as txt178 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/bullet.en.md?type=meta';
import { demos as dm179, frontmatter as fm179, toc as toc179, texts as txt179 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/bullet.zh.md?type=meta';
import { demos as dm180, frontmatter as fm180, toc as toc180, texts as txt180 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/column.en.md?type=meta';
import { demos as dm181, frontmatter as fm181, toc as toc181, texts as txt181 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/column.zh.md?type=meta';
import { demos as dm182, frontmatter as fm182, toc as toc182, texts as txt182 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/funnel.en.md?type=meta';
import { demos as dm183, frontmatter as fm183, toc as toc183, texts as txt183 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/funnel.zh.md?type=meta';
import { demos as dm184, frontmatter as fm184, toc as toc184, texts as txt184 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/liquid.en.md?type=meta';
import { demos as dm185, frontmatter as fm185, toc as toc185, texts as txt185 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/liquid.zh.md?type=meta';
import { demos as dm186, frontmatter as fm186, toc as toc186, texts as txt186 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/sankey.en.md?type=meta';
import { demos as dm187, frontmatter as fm187, toc as toc187, texts as txt187 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/sankey.zh.md?type=meta';
import { demos as dm188, frontmatter as fm188, toc as toc188, texts as txt188 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/violin.en.md?type=meta';
import { demos as dm189, frontmatter as fm189, toc as toc189, texts as txt189 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/violin.zh.md?type=meta';
import { demos as dm190, frontmatter as fm190, toc as toc190, texts as txt190 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/bar-style.en.md?type=meta';
import { demos as dm191, frontmatter as fm191, toc as toc191, texts as txt191 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/bar-style.zh.md?type=meta';
import { demos as dm192, frontmatter as fm192, toc as toc192, texts as txt192 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/component.en.md?type=meta';
import { demos as dm193, frontmatter as fm193, toc as toc193, texts as txt193 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/component.zh.md?type=meta';
import { demos as dm194, frontmatter as fm194, toc as toc194, texts as txt194 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/scrollbar.en.md?type=meta';
import { demos as dm195, frontmatter as fm195, toc as toc195, texts as txt195 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/scrollbar.zh.md?type=meta';
import { demos as dm196, frontmatter as fm196, toc as toc196, texts as txt196 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/statistic.en.md?type=meta';
import { demos as dm197, frontmatter as fm197, toc as toc197, texts as txt197 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/statistic.zh.md?type=meta';
import { demos as dm198, frontmatter as fm198, toc as toc198, texts as txt198 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/plots/bar.en.md?type=meta';
import { demos as dm199, frontmatter as fm199, toc as toc199, texts as txt199 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/plots/bar.zh.md?type=meta';
import { demos as dm200, frontmatter as fm200, toc as toc200, texts as txt200 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/plots/pie.en.md?type=meta';
import { demos as dm201, frontmatter as fm201, toc as toc201, texts as txt201 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/plots/pie.zh.md?type=meta';
import { demos as dm202, frontmatter as fm202, toc as toc202, texts as txt202 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/gauge.en.md?type=meta';
import { demos as dm203, frontmatter as fm203, toc as toc203, texts as txt203 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/gauge.zh.md?type=meta';
import { demos as dm204, frontmatter as fm204, toc as toc204, texts as txt204 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/radar.en.md?type=meta';
import { demos as dm205, frontmatter as fm205, toc as toc205, texts as txt205 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/radar.zh.md?type=meta';
import { demos as dm206, frontmatter as fm206, toc as toc206, texts as txt206 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/stock.en.md?type=meta';
import { demos as dm207, frontmatter as fm207, toc as toc207, texts as txt207 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/stock.zh.md?type=meta';
import { demos as dm208, frontmatter as fm208, toc as toc208, texts as txt208 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/plot-cfg.en.md?type=meta';
import { demos as dm209, frontmatter as fm209, toc as toc209, texts as txt209 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/plot-cfg.zh.md?type=meta';
import { demos as dm210, frontmatter as fm210, toc as toc210, texts as txt210 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/xy-field.en.md?type=meta';
import { demos as dm211, frontmatter as fm211, toc as toc211, texts as txt211 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/xy-field.zh.md?type=meta';
import { demos as dm212, frontmatter as fm212, toc as toc212, texts as txt212 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/area.en.md?type=meta';
import { demos as dm213, frontmatter as fm213, toc as toc213, texts as txt213 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/area.zh.md?type=meta';
import { demos as dm214, frontmatter as fm214, toc as toc214, texts as txt214 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/line.en.md?type=meta';
import { demos as dm215, frontmatter as fm215, toc as toc215, texts as txt215 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/line.zh.md?type=meta';
import { demos as dm216, frontmatter as fm216, toc as toc216, texts as txt216 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/rose.en.md?type=meta';
import { demos as dm217, frontmatter as fm217, toc as toc217, texts as txt217 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/rose.zh.md?type=meta';
import { demos as dm218, frontmatter as fm218, toc as toc218, texts as txt218 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/venn.en.md?type=meta';
import { demos as dm219, frontmatter as fm219, toc as toc219, texts as txt219 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/venn.zh.md?type=meta';
import { demos as dm220, frontmatter as fm220, toc as toc220, texts as txt220 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/pattern.en.md?type=meta';
import { demos as dm221, frontmatter as fm221, toc as toc221, texts as txt221 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/pattern.zh.md?type=meta';
import { demos as dm222, frontmatter as fm222, toc as toc222, texts as txt222 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/tooltip.en.md?type=meta';
import { demos as dm223, frontmatter as fm223, toc as toc223, texts as txt223 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/tooltip.zh.md?type=meta';
import { demos as dm224, frontmatter as fm224, toc as toc224, texts as txt224 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/contact.en.md?type=meta';
import { demos as dm225, frontmatter as fm225, toc as toc225, texts as txt225 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/contact.zh.md?type=meta';
import { demos as dm226, frontmatter as fm226, toc as toc226, texts as txt226 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/upgrade.en.md?type=meta';
import { demos as dm227, frontmatter as fm227, toc as toc227, texts as txt227 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/upgrade.zh.md?type=meta';
import { demos as dm228, frontmatter as fm228, toc as toc228, texts as txt228 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/bar.en.md?type=meta';
import { demos as dm229, frontmatter as fm229, toc as toc229, texts as txt229 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/bar.zh.md?type=meta';
import { demos as dm230, frontmatter as fm230, toc as toc230, texts as txt230 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/box.en.md?type=meta';
import { demos as dm231, frontmatter as fm231, toc as toc231, texts as txt231 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/box.zh.md?type=meta';
import { demos as dm232, frontmatter as fm232, toc as toc232, texts as txt232 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/pie.en.md?type=meta';
import { demos as dm233, frontmatter as fm233, toc as toc233, texts as txt233 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plots/pie.zh.md?type=meta';
import { demos as dm234, frontmatter as fm234, toc as toc234, texts as txt234 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/events.en.md?type=meta';
import { demos as dm235, frontmatter as fm235, toc as toc235, texts as txt235 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/events.zh.md?type=meta';
import { demos as dm236, frontmatter as fm236, toc as toc236, texts as txt236 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/legend.en.md?type=meta';
import { demos as dm237, frontmatter as fm237, toc as toc237, texts as txt237 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/legend.zh.md?type=meta';
import { demos as dm238, frontmatter as fm238, toc as toc238, texts as txt238 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/marker.en.md?type=meta';
import { demos as dm239, frontmatter as fm239, toc as toc239, texts as txt239 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/marker.zh.md?type=meta';
import { demos as dm240, frontmatter as fm240, toc as toc240, texts as txt240 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/slider.en.md?type=meta';
import { demos as dm241, frontmatter as fm241, toc as toc241, texts as txt241 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/slider.zh.md?type=meta';
import { demos as dm242, frontmatter as fm242, toc as toc242, texts as txt242 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/plugin.en.md?type=meta';
import { demos as dm243, frontmatter as fm243, toc as toc243, texts as txt243 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/plugin.zh.md?type=meta';
import { demos as dm244, frontmatter as fm244, toc as toc244, texts as txt244 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/styles/component.md?type=meta';
import { demos as dm245, frontmatter as fm245, toc as toc245, texts as txt245 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plot-api.en.md?type=meta';
import { demos as dm246, frontmatter as fm246, toc as toc246, texts as txt246 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/api/plot-api.zh.md?type=meta';
import { demos as dm247, frontmatter as fm247, toc as toc247, texts as txt247 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/brush.en.md?type=meta';
import { demos as dm248, frontmatter as fm248, toc as toc248, texts as txt248 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/brush.zh.md?type=meta';
import { demos as dm249, frontmatter as fm249, toc as toc249, texts as txt249 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/chord.en.md?type=meta';
import { demos as dm250, frontmatter as fm250, toc as toc250, texts as txt250 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/chord.zh.md?type=meta';
import { demos as dm251, frontmatter as fm251, toc as toc251, texts as txt251 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/color.en.md?type=meta';
import { demos as dm252, frontmatter as fm252, toc as toc252, texts as txt252 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/color.zh.md?type=meta';
import { demos as dm253, frontmatter as fm253, toc as toc253, texts as txt253 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/label.en.md?type=meta';
import { demos as dm254, frontmatter as fm254, toc as toc254, texts as txt254 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/label.zh.md?type=meta';
import { demos as dm255, frontmatter as fm255, toc as toc255, texts as txt255 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/theme.en.md?type=meta';
import { demos as dm256, frontmatter as fm256, toc as toc256, texts as txt256 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/theme.zh.md?type=meta';
import { demos as dm257, frontmatter as fm257, toc as toc257, texts as txt257 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/axis.en.md?type=meta';
import { demos as dm258, frontmatter as fm258, toc as toc258, texts as txt258 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/axis.zh.md?type=meta';
import { demos as dm259, frontmatter as fm259, toc as toc259, texts as txt259 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/data.en.md?type=meta';
import { demos as dm260, frontmatter as fm260, toc as toc260, texts as txt260 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/data.zh.md?type=meta';
import { demos as dm261, frontmatter as fm261, toc as toc261, texts as txt261 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/meta.en.md?type=meta';
import { demos as dm262, frontmatter as fm262, toc as toc262, texts as txt262 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/common/meta.zh.md?type=meta';
import { demos as dm263, frontmatter as fm263, toc as toc263, texts as txt263 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/faq.en.md?type=meta';
import { demos as dm264, frontmatter as fm264, toc as toc264, texts as txt264 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/manual/faq.zh.md?type=meta';
import { demos as dm265, frontmatter as fm265, toc as toc265, texts as txt265 } from '/Users/liaoxiaojuan/work/G2Plot/site/docs/styles/style.md?type=meta';
import { demos as dm266, frontmatter as fm266, toc as toc266, texts as txt266 } from '/Users/liaoxiaojuan/work/G2Plot/site/node_modules/_@antv_dumi-theme-antv@0.3.4@@antv/dumi-theme-antv/dist/pages/Examples/index.js?type=meta';

export { components } from './atoms';
export { tabs } from './tabs';

export const filesMeta = {
  'docs/common/annotations/base-annotation.en': {
    frontmatter: fm0,
    toc: toc0,
    texts: txt0,
    demos: dm0,
  },
  'docs/common/annotations/base-annotation.zh': {
    frontmatter: fm1,
    toc: toc1,
    texts: txt1,
    demos: dm1,
  },
  'docs/common/annotations/region-filter.en': {
    frontmatter: fm2,
    toc: toc2,
    texts: txt2,
    demos: dm2,
  },
  'docs/common/annotations/region-filter.zh': {
    frontmatter: fm3,
    toc: toc3,
    texts: txt3,
    demos: dm3,
  },
  'docs/common/annotations/data-marker.en': {
    frontmatter: fm4,
    toc: toc4,
    texts: txt4,
    demos: dm4,
  },
  'docs/common/annotations/data-marker.zh': {
    frontmatter: fm5,
    toc: toc5,
    texts: txt5,
    demos: dm5,
  },
  'docs/common/annotations/data-region.en': {
    frontmatter: fm6,
    toc: toc6,
    texts: txt6,
    demos: dm6,
  },
  'docs/common/annotations/data-region.zh': {
    frontmatter: fm7,
    toc: toc7,
    texts: txt7,
    demos: dm7,
  },
  'docs/api/components/conversion-tag.en': {
    frontmatter: fm8,
    toc: toc8,
    texts: txt8,
    demos: dm8,
  },
  'docs/api/components/conversion-tag.zh': {
    frontmatter: fm9,
    toc: toc9,
    texts: txt9,
    demos: dm9,
  },
  'docs/api/plots/bidirectional-bar.en': {
    frontmatter: fm10,
    toc: toc10,
    texts: txt10,
    demos: dm10,
  },
  'docs/api/plots/bidirectional-bar.zh': {
    frontmatter: fm11,
    toc: toc11,
    texts: txt11,
    demos: dm11,
  },
  'docs/api/components/annotations.en': {
    frontmatter: fm12,
    toc: toc12,
    texts: txt12,
    demos: dm12,
  },
  'docs/api/components/annotations.zh': {
    frontmatter: fm13,
    toc: toc13,
    texts: txt13,
    demos: dm13,
  },
  'docs/common/annotations/region.en': {
    frontmatter: fm14,
    toc: toc14,
    texts: txt14,
    demos: dm14,
  },
  'docs/common/annotations/region.zh': {
    frontmatter: fm15,
    toc: toc15,
    texts: txt15,
    demos: dm15,
  },
  'docs/common/component-progress.en': {
    frontmatter: fm16,
    toc: toc16,
    texts: txt16,
    demos: dm16,
  },
  'docs/common/component-progress.zh': {
    frontmatter: fm17,
    toc: toc17,
    texts: txt17,
    demos: dm17,
  },
  'docs/api/advanced-plots/facet.en': {
    frontmatter: fm18,
    toc: toc18,
    texts: txt18,
    demos: dm18,
  },
  'docs/api/advanced-plots/facet.zh': {
    frontmatter: fm19,
    toc: toc19,
    texts: txt19,
    demos: dm19,
  },
  'docs/api/components/scrollbar.en': {
    frontmatter: fm20,
    toc: toc20,
    texts: txt20,
    demos: dm20,
  },
  'docs/api/components/scrollbar.zh': {
    frontmatter: fm21,
    toc: toc21,
    texts: txt21,
    demos: dm21,
  },
  'docs/api/components/statistic.en': {
    frontmatter: fm22,
    toc: toc22,
    texts: txt22,
    demos: dm22,
  },
  'docs/api/components/statistic.zh': {
    frontmatter: fm23,
    toc: toc23,
    texts: txt23,
    demos: dm23,
  },
  'docs/api/options/interactions.en': {
    frontmatter: fm24,
    toc: toc24,
    texts: txt24,
    demos: dm24,
  },
  'docs/api/options/interactions.zh': {
    frontmatter: fm25,
    toc: toc25,
    texts: txt25,
    demos: dm25,
  },
  'docs/api/plots/circle-packing.en': {
    frontmatter: fm26,
    toc: toc26,
    texts: txt26,
    demos: dm26,
  },
  'docs/api/plots/circle-packing.zh': {
    frontmatter: fm27,
    toc: toc27,
    texts: txt27,
    demos: dm27,
  },
  'docs/common/annotations/image.en': {
    frontmatter: fm28,
    toc: toc28,
    texts: txt28,
    demos: dm28,
  },
  'docs/common/annotations/image.zh': {
    frontmatter: fm29,
    toc: toc29,
    texts: txt29,
    demos: dm29,
  },
  'docs/common/annotations/shape.en': {
    frontmatter: fm30,
    toc: toc30,
    texts: txt30,
    demos: dm30,
  },
  'docs/common/annotations/shape.zh': {
    frontmatter: fm31,
    toc: toc31,
    texts: txt31,
    demos: dm31,
  },
  'docs/common/component-no-axis.en': {
    frontmatter: fm32,
    toc: toc32,
    texts: txt32,
    demos: dm32,
  },
  'docs/common/component-no-axis.zh': {
    frontmatter: fm33,
    toc: toc33,
    texts: txt33,
    demos: dm33,
  },
  'docs/common/component-polygon.en': {
    frontmatter: fm34,
    toc: toc34,
    texts: txt34,
    demos: dm34,
  },
  'docs/common/component-polygon.zh': {
    frontmatter: fm35,
    toc: toc35,
    texts: txt35,
    demos: dm35,
  },
  'docs/api/plots/ring-progress.en': {
    frontmatter: fm36,
    toc: toc36,
    texts: txt36,
    demos: dm36,
  },
  'docs/api/plots/ring-progress.zh': {
    frontmatter: fm37,
    toc: toc37,
    texts: txt37,
    demos: dm37,
  },
  'docs/common/annotations/html.en': {
    frontmatter: fm38,
    toc: toc38,
    texts: txt38,
    demos: dm38,
  },
  'docs/common/annotations/html.zh': {
    frontmatter: fm39,
    toc: toc39,
    texts: txt39,
    demos: dm39,
  },
  'docs/common/annotations/line.en': {
    frontmatter: fm40,
    toc: toc40,
    texts: txt40,
    demos: dm40,
  },
  'docs/common/annotations/line.zh': {
    frontmatter: fm41,
    toc: toc41,
    texts: txt41,
    demos: dm41,
  },
  'docs/common/annotations/text.en': {
    frontmatter: fm42,
    toc: toc42,
    texts: txt42,
    demos: dm42,
  },
  'docs/common/annotations/text.zh': {
    frontmatter: fm43,
    toc: toc43,
    texts: txt43,
    demos: dm43,
  },
  'docs/common/common-component.en': {
    frontmatter: fm44,
    toc: toc44,
    texts: txt44,
    demos: dm44,
  },
  'docs/common/common-component.zh': {
    frontmatter: fm45,
    toc: toc45,
    texts: txt45,
    demos: dm45,
  },
  'docs/api/advanced-plots/mix.en': {
    frontmatter: fm46,
    toc: toc46,
    texts: txt46,
    demos: dm46,
  },
  'docs/api/advanced-plots/mix.zh': {
    frontmatter: fm47,
    toc: toc47,
    texts: txt47,
    demos: dm47,
  },
  'docs/api/components/tooltip.en': {
    frontmatter: fm48,
    toc: toc48,
    texts: txt48,
    demos: dm48,
  },
  'docs/api/components/tooltip.zh': {
    frontmatter: fm49,
    toc: toc49,
    texts: txt49,
    demos: dm49,
  },
  'docs/common/annotations/arc.en': {
    frontmatter: fm50,
    toc: toc50,
    texts: txt50,
    demos: dm50,
  },
  'docs/common/annotations/arc.zh': {
    frontmatter: fm51,
    toc: toc51,
    texts: txt51,
    demos: dm51,
  },
  'docs/common/crosshairs-text.en': {
    frontmatter: fm52,
    toc: toc52,
    texts: txt52,
    demos: dm52,
  },
  'docs/common/crosshairs-text.zh': {
    frontmatter: fm53,
    toc: toc53,
    texts: txt53,
    demos: dm53,
  },
  'docs/manual/getting-started.en': {
    frontmatter: fm54,
    toc: toc54,
    texts: txt54,
    demos: dm54,
  },
  'docs/manual/getting-started.zh': {
    frontmatter: fm55,
    toc: toc55,
    texts: txt55,
    demos: dm55,
  },
  'docs/manual/plots/histogram.en': {
    frontmatter: fm56,
    toc: toc56,
    texts: txt56,
    demos: dm56,
  },
  'docs/manual/plots/histogram.zh': {
    frontmatter: fm57,
    toc: toc57,
    texts: txt57,
    demos: dm57,
  },
  'docs/manual/plots/waterfall.en': {
    frontmatter: fm58,
    toc: toc58,
    texts: txt58,
    demos: dm58,
  },
  'docs/manual/plots/waterfall.zh': {
    frontmatter: fm59,
    toc: toc59,
    texts: txt59,
    demos: dm59,
  },
  'docs/api/components/legend.en': {
    frontmatter: fm60,
    toc: toc60,
    texts: txt60,
    demos: dm60,
  },
  'docs/api/components/legend.zh': {
    frontmatter: fm61,
    toc: toc61,
    texts: txt61,
    demos: dm61,
  },
  'docs/api/components/slider.en': {
    frontmatter: fm62,
    toc: toc62,
    texts: txt62,
    demos: dm62,
  },
  'docs/api/components/slider.zh': {
    frontmatter: fm63,
    toc: toc63,
    texts: txt63,
    demos: dm63,
  },
  'docs/api/options/animation.en': {
    frontmatter: fm64,
    toc: toc64,
    texts: txt64,
    demos: dm64,
  },
  'docs/api/options/animation.zh': {
    frontmatter: fm65,
    toc: toc65,
    texts: txt65,
    demos: dm65,
  },
  'docs/api/plots/tiny-column.en': {
    frontmatter: fm66,
    toc: toc66,
    texts: txt66,
    demos: dm66,
  },
  'docs/api/plots/tiny-column.zh': {
    frontmatter: fm67,
    toc: toc67,
    texts: txt67,
    demos: dm67,
  },
  'docs/common/animate-option.en': {
    frontmatter: fm68,
    toc: toc68,
    texts: txt68,
    demos: dm68,
  },
  'docs/common/animate-option.zh': {
    frontmatter: fm69,
    toc: toc69,
    texts: txt69,
    demos: dm69,
  },
  'docs/common/component-tiny.en': {
    frontmatter: fm70,
    toc: toc70,
    texts: txt70,
    demos: dm70,
  },
  'docs/common/component-tiny.zh': {
    frontmatter: fm71,
    toc: toc71,
    texts: txt71,
    demos: dm71,
  },
  'docs/common/connected-area.en': {
    frontmatter: fm72,
    toc: toc72,
    texts: txt72,
    demos: dm72,
  },
  'docs/common/connected-area.zh': {
    frontmatter: fm73,
    toc: toc73,
    texts: txt73,
    demos: dm73,
  },
  'docs/common/conversion-tag.en': {
    frontmatter: fm74,
    toc: toc74,
    texts: txt74,
    demos: dm74,
  },
  'docs/common/conversion-tag.zh': {
    frontmatter: fm75,
    toc: toc75,
    texts: txt75,
    demos: dm75,
  },
  'docs/api/components/label.en': {
    frontmatter: fm76,
    toc: toc76,
    texts: txt76,
    demos: dm76,
  },
  'docs/api/components/label.zh': {
    frontmatter: fm77,
    toc: toc77,
    texts: txt77,
    demos: dm77,
  },
  'docs/api/plots/radial-bar.en': {
    frontmatter: fm78,
    toc: toc78,
    texts: txt78,
    demos: dm78,
  },
  'docs/api/plots/radial-bar.zh': {
    frontmatter: fm79,
    toc: toc79,
    texts: txt79,
    demos: dm79,
  },
  'docs/api/plots/word-cloud.en': {
    frontmatter: fm80,
    toc: toc80,
    texts: txt80,
    demos: dm80,
  },
  'docs/api/plots/word-cloud.zh': {
    frontmatter: fm81,
    toc: toc81,
    texts: txt81,
    demos: dm81,
  },
  'docs/common/chart-methods.en': {
    frontmatter: fm82,
    toc: toc82,
    texts: txt82,
    demos: dm82,
  },
  'docs/common/chart-methods.zh': {
    frontmatter: fm83,
    toc: toc83,
    texts: txt83,
    demos: dm83,
  },
  'docs/common/chart-options.en': {
    frontmatter: fm84,
    toc: toc84,
    texts: txt84,
    demos: dm84,
  },
  'docs/common/chart-options.zh': {
    frontmatter: fm85,
    toc: toc85,
    texts: txt85,
    demos: dm85,
  },
  'docs/manual/plots/heatmap.en': {
    frontmatter: fm86,
    toc: toc86,
    texts: txt86,
    demos: dm86,
  },
  'docs/manual/plots/heatmap.zh': {
    frontmatter: fm87,
    toc: toc87,
    texts: txt87,
    demos: dm87,
  },
  'docs/manual/plots/scatter.en': {
    frontmatter: fm88,
    toc: toc88,
    texts: txt88,
    demos: dm88,
  },
  'docs/manual/plots/scatter.zh': {
    frontmatter: fm89,
    toc: toc89,
    texts: txt89,
    demos: dm89,
  },
  'docs/api/components/axis.en': {
    frontmatter: fm90,
    toc: toc90,
    texts: txt90,
    demos: dm90,
  },
  'docs/api/components/axis.zh': {
    frontmatter: fm91,
    toc: toc91,
    texts: txt91,
    demos: dm91,
  },
  'docs/api/options/pattern.en': {
    frontmatter: fm92,
    toc: toc92,
    texts: txt92,
    demos: dm92,
  },
  'docs/api/options/pattern.zh': {
    frontmatter: fm93,
    toc: toc93,
    texts: txt93,
    demos: dm93,
  },
  'docs/api/plots/dual-axes.en': {
    frontmatter: fm94,
    toc: toc94,
    texts: txt94,
    demos: dm94,
  },
  'docs/api/plots/dual-axes.zh': {
    frontmatter: fm95,
    toc: toc95,
    texts: txt95,
    demos: dm95,
  },
  'docs/api/plots/histogram.en': {
    frontmatter: fm96,
    toc: toc96,
    texts: txt96,
    demos: dm96,
  },
  'docs/api/plots/histogram.zh': {
    frontmatter: fm97,
    toc: toc97,
    texts: txt97,
    demos: dm97,
  },
  'docs/api/plots/tiny-area.en': {
    frontmatter: fm98,
    toc: toc98,
    texts: txt98,
    demos: dm98,
  },
  'docs/api/plots/tiny-area.zh': {
    frontmatter: fm99,
    toc: toc99,
    texts: txt99,
    demos: dm99,
  },
  'docs/api/plots/tiny-line.en': {
    frontmatter: fm100,
    toc: toc100,
    texts: txt100,
    demos: dm100,
  },
  'docs/api/plots/tiny-line.zh': {
    frontmatter: fm101,
    toc: toc101,
    texts: txt101,
    demos: dm101,
  },
  'docs/api/plots/waterfall.en': {
    frontmatter: fm102,
    toc: toc102,
    texts: txt102,
    demos: dm102,
  },
  'docs/api/plots/waterfall.zh': {
    frontmatter: fm103,
    toc: toc103,
    texts: txt103,
    demos: dm103,
  },
  'docs/common/column-style.en': {
    frontmatter: fm104,
    toc: toc104,
    texts: txt104,
    demos: dm104,
  },
  'docs/common/column-style.zh': {
    frontmatter: fm105,
    toc: toc105,
    texts: txt105,
    demos: dm105,
  },
  'docs/common/common-iview.en': {
    frontmatter: fm106,
    toc: toc106,
    texts: txt106,
    demos: dm106,
  },
  'docs/common/common-iview.zh': {
    frontmatter: fm107,
    toc: toc107,
    texts: txt107,
    demos: dm107,
  },
  'docs/common/geometry-cfg.en': {
    frontmatter: fm108,
    toc: toc108,
    texts: txt108,
    demos: dm108,
  },
  'docs/common/geometry-cfg.zh': {
    frontmatter: fm109,
    toc: toc109,
    texts: txt109,
    demos: dm109,
  },
  'docs/common/interactions.en': {
    frontmatter: fm110,
    toc: toc110,
    texts: txt110,
    demos: dm110,
  },
  'docs/common/interactions.zh': {
    frontmatter: fm111,
    toc: toc111,
    texts: txt111,
    demos: dm111,
  },
  'docs/manual/introduction.en': {
    frontmatter: fm112,
    toc: toc112,
    texts: txt112,
    demos: dm112,
  },
  'docs/manual/introduction.zh': {
    frontmatter: fm113,
    toc: toc113,
    texts: txt113,
    demos: dm113,
  },
  'docs/manual/plots/bullet.en': {
    frontmatter: fm114,
    toc: toc114,
    texts: txt114,
    demos: dm114,
  },
  'docs/manual/plots/bullet.zh': {
    frontmatter: fm115,
    toc: toc115,
    texts: txt115,
    demos: dm115,
  },
  'docs/manual/plots/column.en': {
    frontmatter: fm116,
    toc: toc116,
    texts: txt116,
    demos: dm116,
  },
  'docs/manual/plots/column.zh': {
    frontmatter: fm117,
    toc: toc117,
    texts: txt117,
    demos: dm117,
  },
  'docs/manual/plots/funnel.en': {
    frontmatter: fm118,
    toc: toc118,
    texts: txt118,
    demos: dm118,
  },
  'docs/manual/plots/funnel.zh': {
    frontmatter: fm119,
    toc: toc119,
    texts: txt119,
    demos: dm119,
  },
  'docs/manual/plots/liquid.en': {
    frontmatter: fm120,
    toc: toc120,
    texts: txt120,
    demos: dm120,
  },
  'docs/manual/plots/liquid.zh': {
    frontmatter: fm121,
    toc: toc121,
    texts: txt121,
    demos: dm121,
  },
  'docs/manual/plots/violin.en': {
    frontmatter: fm122,
    toc: toc122,
    texts: txt122,
    demos: dm122,
  },
  'docs/manual/plots/violin.zh': {
    frontmatter: fm123,
    toc: toc123,
    texts: txt123,
    demos: dm123,
  },
  'docs/api/options/events.en': {
    frontmatter: fm124,
    toc: toc124,
    texts: txt124,
    demos: dm124,
  },
  'docs/api/options/events.zh': {
    frontmatter: fm125,
    toc: toc125,
    texts: txt125,
    demos: dm125,
  },
  'docs/api/options/g2plot.en': {
    frontmatter: fm126,
    toc: toc126,
    texts: txt126,
    demos: dm126,
  },
  'docs/api/options/g2plot.zh': {
    frontmatter: fm127,
    toc: toc127,
    texts: txt127,
    demos: dm127,
  },
  'docs/api/plots/progress.en': {
    frontmatter: fm128,
    toc: toc128,
    texts: txt128,
    demos: dm128,
  },
  'docs/api/plots/progress.zh': {
    frontmatter: fm129,
    toc: toc129,
    texts: txt129,
    demos: dm129,
  },
  'docs/api/plots/sunburst.en': {
    frontmatter: fm130,
    toc: toc130,
    texts: txt130,
    demos: dm130,
  },
  'docs/api/plots/sunburst.zh': {
    frontmatter: fm131,
    toc: toc131,
    texts: txt131,
    demos: dm131,
  },
  'docs/common/annotations.en': {
    frontmatter: fm132,
    toc: toc132,
    texts: txt132,
    demos: dm132,
  },
  'docs/common/annotations.zh': {
    frontmatter: fm133,
    toc: toc133,
    texts: txt133,
    demos: dm133,
  },
  'docs/common/facet-title.en': {
    frontmatter: fm134,
    toc: toc134,
    texts: txt134,
    demos: dm134,
  },
  'docs/common/facet-title.zh': {
    frontmatter: fm135,
    toc: toc135,
    texts: txt135,
    demos: dm135,
  },
  'docs/common/point-style.en': {
    frontmatter: fm136,
    toc: toc136,
    texts: txt136,
    demos: dm136,
  },
  'docs/common/point-style.zh': {
    frontmatter: fm137,
    toc: toc137,
    texts: txt137,
    demos: dm137,
  },
  'docs/common/shape-style.en': {
    frontmatter: fm138,
    toc: toc138,
    texts: txt138,
    demos: dm138,
  },
  'docs/common/shape-style.zh': {
    frontmatter: fm139,
    toc: toc139,
    texts: txt139,
    demos: dm139,
  },
  'docs/common/state-style.en': {
    frontmatter: fm140,
    toc: toc140,
    texts: txt140,
    demos: dm140,
  },
  'docs/common/state-style.zh': {
    frontmatter: fm141,
    toc: toc141,
    texts: txt141,
    demos: dm141,
  },
  'docs/manual/plots/facet.en': {
    frontmatter: fm142,
    toc: toc142,
    texts: txt142,
    demos: dm142,
  },
  'docs/manual/plots/facet.zh': {
    frontmatter: fm143,
    toc: toc143,
    texts: txt143,
    demos: dm143,
  },
  'docs/manual/plots/gauge.en': {
    frontmatter: fm144,
    toc: toc144,
    texts: txt144,
    demos: dm144,
  },
  'docs/manual/plots/gauge.zh': {
    frontmatter: fm145,
    toc: toc145,
    texts: txt145,
    demos: dm145,
  },
  'docs/manual/plots/radar.en': {
    frontmatter: fm146,
    toc: toc146,
    texts: txt146,
    demos: dm146,
  },
  'docs/manual/plots/radar.zh': {
    frontmatter: fm147,
    toc: toc147,
    texts: txt147,
    demos: dm147,
  },
  'docs/api/graphic-style.en': {
    frontmatter: fm148,
    toc: toc148,
    texts: txt148,
    demos: dm148,
  },
  'docs/api/graphic-style.zh': {
    frontmatter: fm149,
    toc: toc149,
    texts: txt149,
    demos: dm149,
  },
  'docs/api/options/shape.en': {
    frontmatter: fm150,
    toc: toc150,
    texts: txt150,
    demos: dm150,
  },
  'docs/api/options/shape.zh': {
    frontmatter: fm151,
    toc: toc151,
    texts: txt151,
    demos: dm151,
  },
  'docs/api/options/theme.en': {
    frontmatter: fm152,
    toc: toc152,
    texts: txt152,
    demos: dm152,
  },
  'docs/api/options/theme.zh': {
    frontmatter: fm153,
    toc: toc153,
    texts: txt153,
    demos: dm153,
  },
  'docs/api/plots/heatmap.en': {
    frontmatter: fm154,
    toc: toc154,
    texts: txt154,
    demos: dm154,
  },
  'docs/api/plots/heatmap.zh': {
    frontmatter: fm155,
    toc: toc155,
    texts: txt155,
    demos: dm155,
  },
  'docs/api/plots/scatter.en': {
    frontmatter: fm156,
    toc: toc156,
    texts: txt156,
    demos: dm156,
  },
  'docs/api/plots/scatter.zh': {
    frontmatter: fm157,
    toc: toc157,
    texts: txt157,
    demos: dm157,
  },
  'docs/api/plots/treemap.en': {
    frontmatter: fm158,
    toc: toc158,
    texts: txt158,
    demos: dm158,
  },
  'docs/api/plots/treemap.zh': {
    frontmatter: fm159,
    toc: toc159,
    texts: txt159,
    demos: dm159,
  },
  'docs/common/coordinate.en': {
    frontmatter: fm160,
    toc: toc160,
    texts: txt160,
    demos: dm160,
  },
  'docs/common/coordinate.zh': {
    frontmatter: fm161,
    toc: toc161,
    texts: txt161,
    demos: dm161,
  },
  'docs/common/drill-down.en': {
    frontmatter: fm162,
    toc: toc162,
    texts: txt162,
    demos: dm162,
  },
  'docs/common/drill-down.zh': {
    frontmatter: fm163,
    toc: toc163,
    texts: txt163,
    demos: dm163,
  },
  'docs/common/legend-cfg.en': {
    frontmatter: fm164,
    toc: toc164,
    texts: txt164,
    demos: dm164,
  },
  'docs/common/legend-cfg.zh': {
    frontmatter: fm165,
    toc: toc165,
    texts: txt165,
    demos: dm165,
  },
  'docs/common/line-style.en': {
    frontmatter: fm166,
    toc: toc166,
    texts: txt166,
    demos: dm166,
  },
  'docs/common/line-style.zh': {
    frontmatter: fm167,
    toc: toc167,
    texts: txt167,
    demos: dm167,
  },
  'docs/common/text-style.en': {
    frontmatter: fm168,
    toc: toc168,
    texts: txt168,
    demos: dm168,
  },
  'docs/common/text-style.zh': {
    frontmatter: fm169,
    toc: toc169,
    texts: txt169,
    demos: dm169,
  },
  'docs/manual/plots/area.en': {
    frontmatter: fm170,
    toc: toc170,
    texts: txt170,
    demos: dm170,
  },
  'docs/manual/plots/area.zh': {
    frontmatter: fm171,
    toc: toc171,
    texts: txt171,
    demos: dm171,
  },
  'docs/manual/plots/line.en': {
    frontmatter: fm172,
    toc: toc172,
    texts: txt172,
    demos: dm172,
  },
  'docs/manual/plots/line.zh': {
    frontmatter: fm173,
    toc: toc173,
    texts: txt173,
    demos: dm173,
  },
  'docs/manual/plots/venn.en': {
    frontmatter: fm174,
    toc: toc174,
    texts: txt174,
    demos: dm174,
  },
  'docs/manual/plots/venn.zh': {
    frontmatter: fm175,
    toc: toc175,
    texts: txt175,
    demos: dm175,
  },
  'docs/api/options/meta.en': {
    frontmatter: fm176,
    toc: toc176,
    texts: txt176,
    demos: dm176,
  },
  'docs/api/options/meta.zh': {
    frontmatter: fm177,
    toc: toc177,
    texts: txt177,
    demos: dm177,
  },
  'docs/api/plots/bullet.en': {
    frontmatter: fm178,
    toc: toc178,
    texts: txt178,
    demos: dm178,
  },
  'docs/api/plots/bullet.zh': {
    frontmatter: fm179,
    toc: toc179,
    texts: txt179,
    demos: dm179,
  },
  'docs/api/plots/column.en': {
    frontmatter: fm180,
    toc: toc180,
    texts: txt180,
    demos: dm180,
  },
  'docs/api/plots/column.zh': {
    frontmatter: fm181,
    toc: toc181,
    texts: txt181,
    demos: dm181,
  },
  'docs/api/plots/funnel.en': {
    frontmatter: fm182,
    toc: toc182,
    texts: txt182,
    demos: dm182,
  },
  'docs/api/plots/funnel.zh': {
    frontmatter: fm183,
    toc: toc183,
    texts: txt183,
    demos: dm183,
  },
  'docs/api/plots/liquid.en': {
    frontmatter: fm184,
    toc: toc184,
    texts: txt184,
    demos: dm184,
  },
  'docs/api/plots/liquid.zh': {
    frontmatter: fm185,
    toc: toc185,
    texts: txt185,
    demos: dm185,
  },
  'docs/api/plots/sankey.en': {
    frontmatter: fm186,
    toc: toc186,
    texts: txt186,
    demos: dm186,
  },
  'docs/api/plots/sankey.zh': {
    frontmatter: fm187,
    toc: toc187,
    texts: txt187,
    demos: dm187,
  },
  'docs/api/plots/violin.en': {
    frontmatter: fm188,
    toc: toc188,
    texts: txt188,
    demos: dm188,
  },
  'docs/api/plots/violin.zh': {
    frontmatter: fm189,
    toc: toc189,
    texts: txt189,
    demos: dm189,
  },
  'docs/common/bar-style.en': {
    frontmatter: fm190,
    toc: toc190,
    texts: txt190,
    demos: dm190,
  },
  'docs/common/bar-style.zh': {
    frontmatter: fm191,
    toc: toc191,
    texts: txt191,
    demos: dm191,
  },
  'docs/common/component.en': {
    frontmatter: fm192,
    toc: toc192,
    texts: txt192,
    demos: dm192,
  },
  'docs/common/component.zh': {
    frontmatter: fm193,
    toc: toc193,
    texts: txt193,
    demos: dm193,
  },
  'docs/common/scrollbar.en': {
    frontmatter: fm194,
    toc: toc194,
    texts: txt194,
    demos: dm194,
  },
  'docs/common/scrollbar.zh': {
    frontmatter: fm195,
    toc: toc195,
    texts: txt195,
    demos: dm195,
  },
  'docs/common/statistic.en': {
    frontmatter: fm196,
    toc: toc196,
    texts: txt196,
    demos: dm196,
  },
  'docs/common/statistic.zh': {
    frontmatter: fm197,
    toc: toc197,
    texts: txt197,
    demos: dm197,
  },
  'docs/manual/plots/bar.en': {
    frontmatter: fm198,
    toc: toc198,
    texts: txt198,
    demos: dm198,
  },
  'docs/manual/plots/bar.zh': {
    frontmatter: fm199,
    toc: toc199,
    texts: txt199,
    demos: dm199,
  },
  'docs/manual/plots/pie.en': {
    frontmatter: fm200,
    toc: toc200,
    texts: txt200,
    demos: dm200,
  },
  'docs/manual/plots/pie.zh': {
    frontmatter: fm201,
    toc: toc201,
    texts: txt201,
    demos: dm201,
  },
  'docs/api/plots/gauge.en': {
    frontmatter: fm202,
    toc: toc202,
    texts: txt202,
    demos: dm202,
  },
  'docs/api/plots/gauge.zh': {
    frontmatter: fm203,
    toc: toc203,
    texts: txt203,
    demos: dm203,
  },
  'docs/api/plots/radar.en': {
    frontmatter: fm204,
    toc: toc204,
    texts: txt204,
    demos: dm204,
  },
  'docs/api/plots/radar.zh': {
    frontmatter: fm205,
    toc: toc205,
    texts: txt205,
    demos: dm205,
  },
  'docs/api/plots/stock.en': {
    frontmatter: fm206,
    toc: toc206,
    texts: txt206,
    demos: dm206,
  },
  'docs/api/plots/stock.zh': {
    frontmatter: fm207,
    toc: toc207,
    texts: txt207,
    demos: dm207,
  },
  'docs/common/plot-cfg.en': {
    frontmatter: fm208,
    toc: toc208,
    texts: txt208,
    demos: dm208,
  },
  'docs/common/plot-cfg.zh': {
    frontmatter: fm209,
    toc: toc209,
    texts: txt209,
    demos: dm209,
  },
  'docs/common/xy-field.en': {
    frontmatter: fm210,
    toc: toc210,
    texts: txt210,
    demos: dm210,
  },
  'docs/common/xy-field.zh': {
    frontmatter: fm211,
    toc: toc211,
    texts: txt211,
    demos: dm211,
  },
  'docs/api/plots/area.en': {
    frontmatter: fm212,
    toc: toc212,
    texts: txt212,
    demos: dm212,
  },
  'docs/api/plots/area.zh': {
    frontmatter: fm213,
    toc: toc213,
    texts: txt213,
    demos: dm213,
  },
  'docs/api/plots/line.en': {
    frontmatter: fm214,
    toc: toc214,
    texts: txt214,
    demos: dm214,
  },
  'docs/api/plots/line.zh': {
    frontmatter: fm215,
    toc: toc215,
    texts: txt215,
    demos: dm215,
  },
  'docs/api/plots/rose.en': {
    frontmatter: fm216,
    toc: toc216,
    texts: txt216,
    demos: dm216,
  },
  'docs/api/plots/rose.zh': {
    frontmatter: fm217,
    toc: toc217,
    texts: txt217,
    demos: dm217,
  },
  'docs/api/plots/venn.en': {
    frontmatter: fm218,
    toc: toc218,
    texts: txt218,
    demos: dm218,
  },
  'docs/api/plots/venn.zh': {
    frontmatter: fm219,
    toc: toc219,
    texts: txt219,
    demos: dm219,
  },
  'docs/common/pattern.en': {
    frontmatter: fm220,
    toc: toc220,
    texts: txt220,
    demos: dm220,
  },
  'docs/common/pattern.zh': {
    frontmatter: fm221,
    toc: toc221,
    texts: txt221,
    demos: dm221,
  },
  'docs/common/tooltip.en': {
    frontmatter: fm222,
    toc: toc222,
    texts: txt222,
    demos: dm222,
  },
  'docs/common/tooltip.zh': {
    frontmatter: fm223,
    toc: toc223,
    texts: txt223,
    demos: dm223,
  },
  'docs/manual/contact.en': {
    frontmatter: fm224,
    toc: toc224,
    texts: txt224,
    demos: dm224,
  },
  'docs/manual/contact.zh': {
    frontmatter: fm225,
    toc: toc225,
    texts: txt225,
    demos: dm225,
  },
  'docs/manual/upgrade.en': {
    frontmatter: fm226,
    toc: toc226,
    texts: txt226,
    demos: dm226,
  },
  'docs/manual/upgrade.zh': {
    frontmatter: fm227,
    toc: toc227,
    texts: txt227,
    demos: dm227,
  },
  'docs/api/plots/bar.en': {
    frontmatter: fm228,
    toc: toc228,
    texts: txt228,
    demos: dm228,
  },
  'docs/api/plots/bar.zh': {
    frontmatter: fm229,
    toc: toc229,
    texts: txt229,
    demos: dm229,
  },
  'docs/api/plots/box.en': {
    frontmatter: fm230,
    toc: toc230,
    texts: txt230,
    demos: dm230,
  },
  'docs/api/plots/box.zh': {
    frontmatter: fm231,
    toc: toc231,
    texts: txt231,
    demos: dm231,
  },
  'docs/api/plots/pie.en': {
    frontmatter: fm232,
    toc: toc232,
    texts: txt232,
    demos: dm232,
  },
  'docs/api/plots/pie.zh': {
    frontmatter: fm233,
    toc: toc233,
    texts: txt233,
    demos: dm233,
  },
  'docs/common/events.en': {
    frontmatter: fm234,
    toc: toc234,
    texts: txt234,
    demos: dm234,
  },
  'docs/common/events.zh': {
    frontmatter: fm235,
    toc: toc235,
    texts: txt235,
    demos: dm235,
  },
  'docs/common/legend.en': {
    frontmatter: fm236,
    toc: toc236,
    texts: txt236,
    demos: dm236,
  },
  'docs/common/legend.zh': {
    frontmatter: fm237,
    toc: toc237,
    texts: txt237,
    demos: dm237,
  },
  'docs/common/marker.en': {
    frontmatter: fm238,
    toc: toc238,
    texts: txt238,
    demos: dm238,
  },
  'docs/common/marker.zh': {
    frontmatter: fm239,
    toc: toc239,
    texts: txt239,
    demos: dm239,
  },
  'docs/common/slider.en': {
    frontmatter: fm240,
    toc: toc240,
    texts: txt240,
    demos: dm240,
  },
  'docs/common/slider.zh': {
    frontmatter: fm241,
    toc: toc241,
    texts: txt241,
    demos: dm241,
  },
  'docs/manual/plugin.en': {
    frontmatter: fm242,
    toc: toc242,
    texts: txt242,
    demos: dm242,
  },
  'docs/manual/plugin.zh': {
    frontmatter: fm243,
    toc: toc243,
    texts: txt243,
    demos: dm243,
  },
  'docs/styles/component': {
    frontmatter: fm244,
    toc: toc244,
    texts: txt244,
    demos: dm244,
  },
  'docs/api/plot-api.en': {
    frontmatter: fm245,
    toc: toc245,
    texts: txt245,
    demos: dm245,
  },
  'docs/api/plot-api.zh': {
    frontmatter: fm246,
    toc: toc246,
    texts: txt246,
    demos: dm246,
  },
  'docs/common/brush.en': {
    frontmatter: fm247,
    toc: toc247,
    texts: txt247,
    demos: dm247,
  },
  'docs/common/brush.zh': {
    frontmatter: fm248,
    toc: toc248,
    texts: txt248,
    demos: dm248,
  },
  'docs/common/chord.en': {
    frontmatter: fm249,
    toc: toc249,
    texts: txt249,
    demos: dm249,
  },
  'docs/common/chord.zh': {
    frontmatter: fm250,
    toc: toc250,
    texts: txt250,
    demos: dm250,
  },
  'docs/common/color.en': {
    frontmatter: fm251,
    toc: toc251,
    texts: txt251,
    demos: dm251,
  },
  'docs/common/color.zh': {
    frontmatter: fm252,
    toc: toc252,
    texts: txt252,
    demos: dm252,
  },
  'docs/common/label.en': {
    frontmatter: fm253,
    toc: toc253,
    texts: txt253,
    demos: dm253,
  },
  'docs/common/label.zh': {
    frontmatter: fm254,
    toc: toc254,
    texts: txt254,
    demos: dm254,
  },
  'docs/common/theme.en': {
    frontmatter: fm255,
    toc: toc255,
    texts: txt255,
    demos: dm255,
  },
  'docs/common/theme.zh': {
    frontmatter: fm256,
    toc: toc256,
    texts: txt256,
    demos: dm256,
  },
  'docs/common/axis.en': {
    frontmatter: fm257,
    toc: toc257,
    texts: txt257,
    demos: dm257,
  },
  'docs/common/axis.zh': {
    frontmatter: fm258,
    toc: toc258,
    texts: txt258,
    demos: dm258,
  },
  'docs/common/data.en': {
    frontmatter: fm259,
    toc: toc259,
    texts: txt259,
    demos: dm259,
  },
  'docs/common/data.zh': {
    frontmatter: fm260,
    toc: toc260,
    texts: txt260,
    demos: dm260,
  },
  'docs/common/meta.en': {
    frontmatter: fm261,
    toc: toc261,
    texts: txt261,
    demos: dm261,
  },
  'docs/common/meta.zh': {
    frontmatter: fm262,
    toc: toc262,
    texts: txt262,
    demos: dm262,
  },
  'docs/manual/faq.en': {
    frontmatter: fm263,
    toc: toc263,
    texts: txt263,
    demos: dm263,
  },
  'docs/manual/faq.zh': {
    frontmatter: fm264,
    toc: toc264,
    texts: txt264,
    demos: dm264,
  },
  'docs/styles/style': {
    frontmatter: fm265,
    toc: toc265,
    texts: txt265,
    demos: dm265,
  },
  'dumi-theme-antv-example-list-zh': {
    frontmatter: fm266,
    toc: toc266,
    texts: txt266,
    demos: dm266,
  },
}

// generate demos data in runtime, for reuse route.id to reduce bundle size
export const demos = Object.entries(filesMeta).reduce((acc, [id, meta]) => {
  // append route id to demo
  Object.values(meta.demos).forEach((demo) => {
    demo.routeId = id;
  });
  // merge demos
  Object.assign(acc, meta.demos);

  // remove demos from meta, to avoid deep clone demos in umi routes/children compatible logic
  delete meta.demos;

  return acc;
}, {});
