name: 🚀 Auto Release
on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && startsWith(github.event.head_commit.message , 'chore(release):')" # commit 记录带 'chore(release):' 关键词

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16 # semantic-release 需要 >= 16 的 Node.js 环境

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn release     

      # G2 栈技术交流群
      - name: Release success ding talk official group notify
        if: ${{ success() }}
        uses: visiky/dingtalk-release-notify@main
        with:
          DING_TALK_TOKEN: ${{ secrets.DING_TALK_TOKENS}}
          notify_title: '🎉 G2Plot 发布 release {release_tag} 🎉'
          notify_body: '## { title }<hr /> ![](https://gw.alipayobjects.com/zos/antfincdn/AdgOtrq%26KF/G2Plot.png) <hr /> { body } <hr />'
          notify_footer: '> 前往 [**G2Plot Releases**]({ release_url }) 查看完整信息.'
          at_all: true

      # 发布失败推送通知内部开发群
      - name: Release failed ding talk dev group notify
        if: ${{ failure() }}
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DEV_GROUP_DING_TOKEN }}
          body: |
            {
              "msgtype": "link",
              "link": {
                "title": "🚨 自动发布失败",
                "text": "🔗 请点击链接查看具体原因, 及时修复 🚑",
                "messageUrl": "https://github.com/antvis/G2Plot/actions/workflows/auto-release.yml",
                "picUrl": "https://gw.alipayobjects.com/zos/antfincdn/AdgOtrq%26KF/G2Plot.png"
              }
            }