name: CI

on: [push]

jobs:
  setup:
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
        env:
          CI: true
  lint:
    steps:
      - name: lint
        run: |
          npm run lint
  build:
    steps:
      - name: build
        run: |
          npm run build
  test:
    steps:
      - name: test
        run: |
          npm test -- --coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
