name: Deploy

on:
  workflow_dispatch:
  release:
    types: [created, edited]

jobs:
  build:
    runs-on: ubuntu-latest # change to macOS-latest if need to run ci/test
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: npm run lint

  deploy-site:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd site
      - run: yarn install
      - run: npm run build
      - run: |
          cd ..
          git init
          git config --local user.name antv
          git config --local user.email antv@antfin.com
          mv site/dist ./
          git add dist -f
          git commit -m "update by release action"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.PERSONAL_ACCESS_TOKEN}}
          branch: gh-pages
          force: true
