name: Deploy

on:
  workflow_dispatch:
  release:
    types: [created, edited]

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: cd site && yarn install
      - run: npm run site:build
      - run: cp ./site/CNAME ./site/dist/CNAME
      - run: |
          cd site/dist
          git init
          git config --local user.name antv
          git config --local user.email antv@antfin.com
          git add .
          git commit -m "update by release action"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.PERSONAL_ACCESS_TOKEN}}
          directory: site/dist
          branch: gh-pages
          force: true
