name: Npm publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # change to macOS-latest if need to run ci/test
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: npm run lint
      - run: npm run build

  publish-site:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
